spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/farmers_fresh_market

  mail:
    host: smtp.gmail.com
    port: 587
    username: kethavathraghu1646@gmail.com
    password: Raghu@123$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwtSecret: your_super_secret_jwt_key_here_long_enough
  jwtExpirationMs: 86400000